### ISSUE TITLE
pdf_writer.py not properly configured for mac

### ISSUE THREAD

**Issue by bkoatz** [subalterngames/talmudifier#1]
mac doesn't have .exe's either. is this properly configured?        

if platform == "linux":
        call(
            ["xelatex",
             "-output-directory", str(Path(output_directory).resolve()),
             "-jobname", filename, doc],
            stdout=open(devnull, "wb"))
        else:
            call(['xelatex.exe',
                  '-output-directory',
                  str(Path(output_directory).resolve()),
                  '-job-name=' + filename,
                  doc],
                 stdout=open(devnull, "wb"))

**Comment by subalterngames** [comment]
@bkoatz See #4 

(Thanks for the tickets by the way!!)
